version: '3.3'
services:
  # selenium hub
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=0
      - GRID_THROW_ON_CAPABILITY_NOT_PRESENT=true
      - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
      - GRID_BROWSER_TIMEOUT=15000
      - GRID_TIMEOUT=30000
      - GRID_CLEAN_UP_CYCLE=30000
      - GRID_MAX_SESSION=200

  # selenium node
  firefox:
    image: selenium/node-firefox:3.141.5-astatine
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=false
      - NODE_MAX_INSTANCES=50
      - NODE_MAX_SESSION=50
      - NODE_REGISTER_CYCLE=5000
      - DBUS_SESSION_BUS_ADDRESS=/dev/null

  solr:
    image: "solr:7.3.1"
    container_name: "solr"
    depends_on:
      - selenium-hub
    ports:
     - "8983:8983"
    # volumes:
      # - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  
  # apache nutch
  nutch:
    build: .
    depends_on:
      - solr
    container_name: "nutch"    
          #image: "apache/nutch:release-1.15"
          #links:
          #- solr
    environment: 
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    working_dir: /root/nutch
    #    command: '/root/nutch/bin/crawl -i -D solr.server.url=http://solr:8983/solr/mycore -s urls crawl 1'
    volumes:
        - ./nutch/index-writers.xml:/root/nutch/conf/index-writers.xml
        - ./nutch/nutch-site.xml:/root/nutch/conf/nutch-site.xml
        - ./nutch/agents.txt:/root/nutch/conf/agents.txt
        - ./nutch/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt
        - ./nutch/seed.txt:/root/nutch/urls/seed.txt
    stdin_open: true
# volumes:
#   data:
